# Generated by Django 2.0 on 2019-04-15 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingClassQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question', verbose_name='问题')),
            ],
            options={
                'verbose_name': '班级问题',
                'verbose_name_plural': '班级问题',
            },
        ),
        migrations.RenameField(
            model_name='teachingclass',
            old_name='weekTh',
            new_name='week',
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='group_id',
            field=models.CharField(editable=False, max_length=100, verbose_name='群组ID'),
        ),
        migrations.AlterField(
            model_name='teachingclass',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教师名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, default='img/default.jpg', null=True, upload_to='%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.CharField(default='', editable=False, max_length=200, verbose_name='融云用户token'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='whitelist',
            field=models.ManyToManyField(blank=True, null=True, to='api.Whitelist', verbose_name='白名单应用'),
        ),
        migrations.AddField(
            model_name='teachingclassquestion',
            name='teachingClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TeachingClass', verbose_name='教学班'),
        ),
    ]
